### ISSUE TITLE
 cannot import name 'EmbedOrUploadBlock' from 'notion.block' 

### ISSUE THREAD

**Issue by ThinkSalat** [Cobertos/md2notion#62]
I'm getting the following error on both mac and windows trying to run this thing

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/md2notion/__main__.py", line 2, in <module>
    from .upload import cli
  File "/opt/homebrew/lib/python3.11/site-packages/md2notion/upload.py", line 11, in <module>
    from notion.block import EmbedOrUploadBlock, CollectionViewBlock, PageBlock
ImportError: cannot import name 'EmbedOrUploadBlock' from 'notion.block' (/opt/homebrew/lib/python3.11/site-packages/notion/block/__init__.py)
`

**Comment by NeoFantom** [comment]
Same for me. Any help?
