### ISSUE TITLE
requests.exceptions.HTTPError: Something went wrong. (400)

### ISSUE THREAD

**Issue by FeixiangChu** [Cobertos/md2notion#64]
Initializing Notion.so client...
Getting target PageBlock...
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/md2notion/__main__.py", line 5, in <module>
    cli(sys.argv[1:])
  File "/opt/anaconda3/lib/python3.9/site-packages/md2notion/upload.py", line 199, in cli
    page = client.get_block(args.page_url)
  File "/opt/anaconda3/lib/python3.9/site-packages/notion/client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "/opt/anaconda3/lib/python3.9/site-packages/notion/client.py", line 162, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "/opt/anaconda3/lib/python3.9/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "/opt/anaconda3/lib/python3.9/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "/opt/anaconda3/lib/python3.9/site-packages/notion/client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Something went wrong. (400)

**Comment by snaerseljan** [comment]
@FeixiangChu did you manage to fix it?
